ansible_connection: network_cli
ansible_network_os: edgeswitch
ansible_user: ubnt
ansible_password: "{{ lookup('netbox_secrets', device=inventory_hostname, secret_name=ansible_user) }}"
ansible_become: yes
ansible_become_method: enable
ansible_become_pass: "{{ ansible_password }}"
ansible_python_interpreter: auto_silent
